## post request for users controller

POST http://localhost:3000/users
Content-Type: application/json
{}

POST http://localhost:3000/users
Content-Type: application/json
{
    "email": "anubhavbisht98@gmail.com",
    "password" : "asdf"
}