POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTc0MDE5NDY0NCwiZXhwIjoxNzQwMjgxMDQ0LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Axd_S5JTeQqVrxd3uSI1ORfXGRx41DMtjlqMfuO2KjI"
}